---
- name: First play 
  hosts: myservers
  gather_facts: False 
  tasks:
    - name: play1-task1
      command: hostname
    - name: play1-task2
      command: hostname

- name: Second Play 
  hosts: workers
  #gather_facts: False 
  tasks:
    - name: play2-task1
      command: hostname
    - name: play2-task2
      command: hostname
