--- 
- name: Check if Apache is working 
  hosts: myservers 
  become: true 

  tasks:
    - name: Start apache2 
      service:
        name: apache2 
        state: started

    - name: Create index.html using jinja2 
      template:
        src: index.j2
        dest: /var/www/html/index.html
