---
- hosts: all 
  become: true
  vars:
    mylist:
      - testuser1
      - testuser2
  tasks:
    - name: add users 
      user:
        name: "{{ item }}"
        state: present 
      loop: "{{ mylist }}"

